quickstep: Fix race condition causing NPE in AbsSwipeUpHandler
A NullPointerException can occur in `updateLauncherTransitionProgress` due
to a race condition.

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.quickstep.util.AnimatorControllerWithResistance.setProgress(float, float)' on a null object reference
	at com.android.quickstep.AbsSwipeUpHandler.lambda$updateLauncherTransitionProgress$12(AbsSwipeUpHandler.java:928)
	at com.android.quickstep.AbsSwipeUpHandler.$r8$lambda$MzA239vSgHIZLvTtHDU-xzeIMEk(AbsSwipeUpHandler.java:0)
	at com.android.quickstep.AbsSwipeUpHandler$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:0)

Signed-off-by: Dmitrii <bankersenator@gmail.com>